### ISSUE TITLE
Limiting the number of selections

### ISSUE THREAD

**Issue by sandino** [yourlabs/django-autocomplete-light#1006]
Select2 out of the box [allows to limit the number of selections](https://select2.org/selections#limiting-the-number-of-selections). When I add script

```
$("#id_my-select-field").select2({
  maximumSelectionLength: 2
});
```

the widget just stops working. It doesn't even query the database.

Is it possible to use this feature with DAL?

**Comment by gagarski** [comment]
> When I add script the widget just stops working. It doesn't even query the database.

It happens because you are trying to initialize Select2 which DAL already has done before. 

Select2 has an alternative way to pass the arguments to the widget: [HTML data-attributes](https://select2.org/configuration/data-attributes) which is good with Django widgets approach. You can simply pass a dictionary with HTML attributes to your widget.

**Comment by sandino** [comment]
@gagarski Thanks a lot!

I confirm that this method works

    attrs={'data-maximum-selection-length': 3}
