### ISSUE TITLE
Security: /autocomplete/ URL is open for everyone

### ISSUE THREAD

**Issue by sb83** [yourlabs/django-autocomplete-light#373]
All registered autocomplete classes are open for everyone, for example if you open http://site.com/autocomplete/ this will show page like as follows

```
List of your 1 registered autocompletes
MyModelAutocomplete 	/autocomplete/MyModelAutocomplete/
```

This might be a security breach if someone use autocomplete only for Django admin, the attacker can see all the autocomplete data/values without any authorization. There should be a way to deny access to this url or autocomplete classes should not be exposed here in any way.

**Comment by jpic** [comment]
Are you sure this URL doesn't respond with HTTP 403 when you are not
authenticated as superuser? In that case you might have a bigger security
issue in your project.

Also, did you read the section on security in the docs to secure each
autocomplete?

**Comment by sb83** [comment]
My fault, this is not a but of this module. URL is not available for anonymous users.

**Comment by jpic** [comment]
Good news, thanks for your feedback. I though maybe a custom auth backend
was broken and it waa openbar on confidential customer data, hehehehe

Iirc we have no regression test for that view because it relies on a
handful of well tested operations, but coverage results would tell for sure.

Would you like to contribute a test case to ensure that this view responds
with 200 for superadmins and 403 for others ? We hopefully all agree that
security is a feature that should be tested. It's also part of the advanced
training you know you really want !

Rock'on
