### ISSUE TITLE
Trouble using autocomplete_light

### ISSUE THREAD

**Issue by ssocias** [yourlabs/django-autocomplete-light#384]
Hello,

I have been trying for quite a while to get autocomplete light working with my project. I'm trying to add another popup window outside the admin. I'm new to Django and am at a loss on what else to do- I've been trying for days. Is there any way you can help me get autocomplete light working with my project?
I've tried requesting you on "hackhands" but no luck....any help would be VERY much appreciated. 
I have read the documentation but am still very lost.

Thank you!
Stephanie

**Comment by jpic** [comment]
Did you read
http://django-autocomplete-light.readthedocs.org/en/stable-2.x.x/faq.html#how-to-ask-for-help
?​
and http://docs.yourlabs.org/en/latest/guidelines.html#asking-for-help also
might help

and http://whathaveyoutried.com

**Comment by ssocias** [comment]
Hello,

Yes I posted [my question] a few days ago on stackoverflow
(http://stackoverflow.com/questions/29313482/autocomplete-light-for-adding-popup-outside-the-admin)

**Comment by blueyed** [comment]
@ssocias 
Also after reading your SO post, it's still not clear what the actual problem is - although that provides more information at least.

What completions do you expect?
Have you registered the completions?

Apart from that you might have luck with `import ipdb; ipdb.set_trace()` at the right place to debug what's going on.

**Comment by jpic** [comment]
Answered on SO.
