### ISSUE TITLE
Widget (js) cannot be passed overrides

### ISSUE THREAD

**Issue by parasgithub** [yourlabs/django-autocomplete-light#403]
In widget.js, when initializeAutocomplete() is called, it tries to initialize the autocomplete without any overrides. We cannot add overrides in a javascript object; the only way seems to be to use data-autocomplete- overrides.

**Comment by jpic** [comment]
Hello,

We could not reproduce your issue. If it's still a problem for you, please
respond to this issue using the following template:


    OS Version:
    Python version:
    Django version:
    App version:
    Database version (if appliable):
    Database driver version (if appliable):
    Browser version (if appliable):

    Traceback (please paste the COMPLETE traceback here):



    Models (only paste relevant section):



    autocomplete_light_registry (only paste relevant section):



    javascript / html if relevant:



    How to reproduce this bug:

    -
    -
    -

    Excepted result:



    Actual result:



If you want a almost garanteed fast answer, then instead of pasting
Models/autocomplete_light_registry/javascript/html above, you could:

- fork the repo,
- reproduct your issue in a new, simple app in
`autocomplete_light/example_apps`
- it should be reproducible in `test_project/manage.py runserver`.

See details in community documentation: http://docs.yourlabs.org

Thanks a lot for helping django-autocomplete-light better.

Sincerely

YourLabs core-dev team
