### ISSUE TITLE
feature: disable the auto hilight on search ?

### ISSUE THREAD

**Issue by superzazu** [yourlabs/django-autocomplete-light#443]
That would be great to disable the auto-hilight when searching.

https://github.com/yourlabs/jquery-autocomplete-light/blob/master/dist/jquery.autocomplete-light.js#L493

**Comment by jpic** [comment]
That would be all right technically, but why would someone want that ?

**Comment by superzazu** [comment]
In the case when you have autocompletion with a traditional search field redirecting to a search page (like steampowered.com)

**Comment by jpic** [comment]
I see, the actual behavior prevents that. So, one fix would be to add a
simple choice that would redirect to the search page at the top of your
autocomplete box template. Then, the first choice would cause a redirect to
the search page. Would that work for you ?

**Comment by EliotBerriot** [comment]
Hi, I work with @superzazu.

Your solution would work, however, it would require to change our templates, and to do some CSS to mask the first choice. 

Since a lot of autocompletes (like Google's, for exemple) does not select the first choice by default,
it seems okay to me to add this in autocomplete-light.

We were thinking about an argument for the `yourlabsAutocomplete` function, something like:

    $('#yourInput').yourlabsAutocomplete({
        url: '{% url "your_autocomplete_url" %}',
        choiceSelector: 'a',
        autoHilightFirst: false,
    });
    
If `autoHilightFirst` defaults to true, I think it keeps backward compatibility.

**Comment by jpic** [comment]
Don't get me wrong, I don't have anything against adding this feature, but
we're not supposed to change code without adding test code. So far we have
selenium tests inside django-autocomplete-light which partially cover the
JS. The current idea is to try to start adding unit tests inside
jquery-autocomplete-light and for the moment well I couldn't move forward
on that because there are more pressing issues (#442 namely).

So it seems wise to try to find a way to solve your actual problem with the
current codebase because adding a test for this would either require more
selenium tests either get started with jquery-autocomplete-light's own
tests - which are currently to be started ;)

Correct me if I'm wrong, but you already have a custom template for this
feature don't you ?

What kind of server-side code is filling this autocomplete box ? Isn't it a
custom view ?

In which case would you want to mask the first choice ? That I didn't
understand at all.

Anyway, if you're up to contributing tests for this, be it in django with
selenium or in jquery-autocomplete-light (which I'd prefer) then I'm all
for having your PR ;)

**Comment by EliotBerriot** [comment]
Thank you for you fast answers. We totally understand there are more important things to solve right now. I'll submit a PR in jquery-autocomplete when I have some time.

**Comment by jpic** [comment]
Thinks was fixed by @superzazu in yourlabs/jquery-autocomplete-light#9.

Grats B)
