### ISSUE TITLE
Should the "change related button" be clickable when the input field is empty?

### ISSUE THREAD

**Issue by gonzalobustos** [yourlabs/django-autocomplete-light#472]
Hello, I'm using django-autocomplete-light with [django-suit] (http://djangosuit.com/) administrator and I have the problem that the change button next to the input field is not "disabled" when the input is empty, allowing me to click it and get a 404 error ("object with primary key u'null' does not exist").

The same error occurs in the [demo app] (http://jpic.pythonanywhere.com/admin/create_choice_on_the_fly/fly/add/) you linked at the readme.

Any help? Is this a bug or an expected behaviour? Thanks!

**Comment by jpic** [comment]
That might depend on the django version ,we need a selenium test for that and let travis tell us.

**Comment by nchampsavoir** [comment]
I'm using Django 1.8 + Django Suit and I've got the exact same problem.

**Comment by nchampsavoir** [comment]
The problem is in the file [jquery-autocomplete-light/src/django_admin.js](https://github.com/yourlabs/jquery-autocomplete-light/blob/master/src/django_admin.js) on line 13.

Value for empty field is null not undefined (I don't know if due to django or django suit...) so instead of 
`if (value !== undefined) {`, line should be `if (value !== undefined && value !== null) {`,

At least it works for me. :)

**Comment by jpic** [comment]
Thanks, it should be fixed in pull #499, please check it out.
