### ISSUE TITLE
Autocomplete "no matches found" lowercased

### ISSUE THREAD

**Issue by jonashaag** [yourlabs/django-autocomplete-light#493]
In the German translation, the "no matches found" text seems to be lowercased:

![screen shot 2015-09-16 at 13 43 27](https://cloud.githubusercontent.com/assets/175722/9903735/01400c64-5c79-11e5-8e7f-e6f1cb004458.png)

This should read "Keine Treffer gefunden", like it's in the localization file.

**Comment by jpic** [comment]
Here: https://github.com/yourlabs/django-autocomplete-light/blob/master/autocomplete_light/autocomplete/base.py#L187

Since backward compatibility is king here, I suggest we get the translation, check if the first letter is capitalized, and only call `.capitalize()` if it is not. We'd need a test case for that too. Do you want to make the PR ? Is it the kind of things you're into or would you rather have somebody else take care of that one ?

**Comment by jonashaag** [comment]
Do you really think that backwards compatibility is so important here? We can easily say in the release notes that the string is now left unmodified, and if someone relies on the case of the letters, it's easily fixed.

**Comment by jpic** [comment]
On Tue, Sep 22, 2015 at 10:24 AM, Jonas Haag <notifications@github.com>
wrote:

> Do you really think that backwards compatibility is so important here? We
> can easily say in the release notes that the string is now left unmodified,
> and if someone relies on the case of the letters, it's easily fixed.


Right but then we can't put it in a minor version release, we'd have to
release this as 2.3.0.

-- 
http://yourlabs.org <http://blog.yourlabs.org>
Customer is king - Le client est roi - El cliente es rey.

**Comment by jonashaag** [comment]
OK, let's put make this part of the 2.3 milestone then.

**Comment by jonashaag** [comment]
Could you add this to the 2.3 GitHub milestone so we don't lose it?

**Comment by jpic** [comment]
To be clear, we just have to remove the .capitalize() call here ?

**Comment by jpic** [comment]
Closing in favor of PR #548
