### ISSUE TITLE
Uncaught TypeError: Cannot read property 'fn' of undefined for autocomplete.js

### ISSUE THREAD

**Issue by soulraven** [yourlabs/django-autocomplete-light#533]
i get this error when i try to load the autocomplete.js the error is on row 126,
$.fn.yourlabsRegistry = function(key, value) {......

**Comment by jpic** [comment]
jquery is not loaded before autocomplete.js loads

**Comment by soulraven** [comment]
i have found the problem, i have to load the autocomplete_light/static.html inside admin_tools, and this is a real chalange

**Comment by jpic** [comment]
Please make sure that you have read the install docs, particularly from here: http://django-autocomplete-light.readthedocs.org/en/master/install.html#ensure-you-understand-django-contrib-staticfiles

**Comment by soulraven** [comment]
All the static files are ok, because if i do the modifications without admin_tools is working just fine, even if the jquery lib is loaded twice for no reason.

I thing the best option is to use class Media but when is called, to load the base.html.
When class Media is used the file position is loaded ok, after all the js files that django admin loads default,

The problem is that django-autocomplete-light is not tested with admin_tools and in docs is nothing about this.

**Comment by jpic** [comment]
On Wed, Dec 2, 2015 at 10:14 PM, Zaharia Constantin <
notifications@github.com> wrote:

> All the static files are ok, because if i do the modifications without
> admin_tools is working just fine, even if the jquery lib is loaded twice
> for no reason.
>
> Obviously, it's not loaded right.

> I thing the best option is to use class Media but when is called, to load
> the base.html.
> When class Media is used the file position is loaded ok, after all the js
> files that django admin loads default,
>
Oh, we used to do that, of course ;) If we don't anymore, it's for a
reason, that's all in the message of the git commit that does it, probably
even in the changelog :)

> The problem is that django-autocomplete-light is not tested with
> admin_tools and in docs is nothing about this.
>
Yeah, the problem is that nobody has yet contributed an example project
with regression tests. Because if someone had, we'd be able to garantee
that it works and that there is no regression for ever, and ever, and ever !

If you want to maintain admin-plus support in DAL you're welcome to join
the team for that ;)

Anything else ?

-- 
http://yourlabs.org <http://blog.yourlabs.org>
Customer is king - Le client est roi - El cliente es rey.

**Comment by soulraven** [comment]
For the moment no, i will try to find a solution for admin_tools and how the files are loaded

**Comment by jpic** [comment]
Well if you need any further help, we've got some pointers here:

http://django-autocomplete-light.readthedocs.org/en/master/faq.html#how-to-ask-for-help
