### ISSUE TITLE
Preferred way to listen for autocomplete change event for 2.2.x branch is ...? 

### ISSUE THREAD

**Issue by mpasternak** [yourlabs/django-autocomplete-light#545]
Hi,

I'm asking about javascript. 

I used this method in my code to catch "changed" event emitted when the autocomplete is changed:

        $("body").on("change", function(e) {
        ....
        }

The deal is, that when I migrate from 2.1.1 to 2.2.0 this method actually stops working for autocomplete widgets. There's something very wrong - it works for every other HTML element, make it select or text, whatever, but I'm unable to actually receive any events produced by autocompletes. It looks like the change event is actually surpassed there. 

So, my question, not an issue actually: what's the preferred method of listening for a change event for 2.2.x branch? I'd love to document it.

**Comment by jpic** [comment]
What do you mean "autocomplete change" ? I thought maybe binding to [Autocomplete.selectChoice](https://github.com/yourlabs/jquery-autocomplete-light/blob/master/src/autocomplete.js#L39) or [Widget.widgetSelectChoice](https://github.com/yourlabs/jquery-autocomplete-light/blob/master/src/widget.js#L91) would be ok.

I don't think that [dependent autocomplete docs](http://dal-yourlabs.rhcloud.com/admin/dependant_autocomplete/dummy/add/) are broken neither because if i select france in the [demo](http://dal-yourlabs.rhcloud.com/admin/dependant_autocomplete/dummy/add/) then i can select "Paris" as city, but not "Parissss FAKE" (in the "rb" country).

Do you think there's a regression ? Could you maybe show some code about it ?

**Comment by mpasternak** [comment]
I'm investigating. 

I tried to catch [this event](https://github.com/yourlabs/jquery-autocomplete-light/blob/master/src/widget.js#L218) with the `$("body").on("change", function(e) { ...}` thing, as I wrote, it catches everything but not this thing. Am I doing something wrong?

**Comment by mpasternak** [comment]
Hi,

no bugs on django-autocomplete-light side, hopefully.

I used multiple versions of jQuery in my admin - `django.jQuery`, and `django-grappelli`'s jQuery `grp.jQuery`. 

I installed my app's signal handlers using django.jQuery module, while autocomplete-light was using other jQuery, installed as global `$`.  

It looks like "core" HTML controls, like an ordinary select generate events that can be caught by all jQuery modules running on the web page. On the other hand, when it comes to custom events like "selectChoice" signal, I am able to catch it only with the jQuery it was triggered with. 

Thanks for your help.

**Comment by jpic** [comment]
Nice, the change event still works ?

In v3 we will run tests against grapelli as well ;) #549

**Comment by mpasternak** [comment]
Change event works too.

**Comment by jpic** [comment]
Nice, thx m8

**Comment by CodefroesPuc** [comment]
Hi, was this documented?

I have the same problem, but I couldn't work out how to solve it.

What I am trying to achieve is similar to what the linked_data example does, but outside the admin. But when I change the selection in the parent select, the 'change' event is not triggered so the "child" select doesn't get its value set to `null`.

I hope I could make myself clear.

**Comment by mpasternak** [comment]
@CodefroesPuc , you're on branch 2.2.x?

**Comment by CodefroesPuc** [comment]
I'm actually using 3.2.10. I installed using pip.
