### ISSUE TITLE
'vendor/select2/node_modules' 41MB after collectstatic?

### ISSUE THREAD

**Issue by adamb70** [yourlabs/django-autocomplete-light#646]
I know select2 is an unrelated package so this may not be the best place to ask this, but how much of the `node_modules` folder is necessary? It just seems odd that this folder takes up 95% of the whole `autocomplete_light` static files. Should probably mention that I'm using V3.1.3

**Comment by jpic** [comment]
Absolutely none, 10MB for the last release, that's way too much, thanks for reporting !!

Several things are wrong here, I need to automate the release process because there's been too many human mistakes this year, also perhaps move the submodule somewhere else and just symlink the files we need like in DAL v2's jquery-autocomplete-light submodule ... but it's 2AM here so I'm not going to take any other action now except going to sleep.

It should be fine in 3.1.4.

A pull request to fix MANIFEST.in and or move the submodule would be really appreciated ! Otherwise I'll probably wait until this becomes an impediment again, next broken release xD

Thanks again !
