### ISSUE TITLE
select2 and i18n

### ISSUE THREAD

**Issue by dotmobo** [yourlabs/django-autocomplete-light#650]
Hi,

How do you enable i18n for select2 ? I use django-autocomplete-light v3.1.4 and my js console shows me the following message : 

Select2: The language file for "./i18n/fr" could not be automatically loaded. A fallback will be used instead.

Thank you for your help

**Comment by jpic** [comment]
Did you include select2's translation file ?

**Comment by dotmobo** [comment]
My bad. The problem happened because i added the translation file BEFORE adding the select2 file. Thank you :)

**Comment by LensHunnel** [comment]
Hi,
I've the same issue. select2's translation file is loaded by the browser after select2 file : 
<script type="text/javascript" src="/static/autocomplete_light/autocomplete.init.js"></script>
<script type="text/javascript" src="/static/autocomplete_light/vendor/select2/dist/js/select2.js"></script>
<script type="text/javascript" src="/static/autocomplete_light/select2.js"></script>
<script type="text/javascript" src="/static/autocomplete_light/jquery.init.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/i18n/fr.js"></script>

I've the following message with or without the select2's translation file:

```Select2: The language file for "./i18n/fr" could not be automatically loaded. A fallback will be used instead.```

**Comment by maratumba** [comment]
I have the same problem with 'tr', any solutions to this?

**Comment by maximilian** [comment]
I believe to have found a solution for this. The problem seems to lie in the fact that the translation file is loaded after all the select2 js files. As a result, the select2 files fail to find the translation file, giving the warning OP is getting. I have found the ideal order for the js files to be loaded are:

1. jquery
2. autocomplete.init.js
3. select2.full.js
4. translation file (e.g. fr.js)
5. select2.js

The library makes use of the media class within the Select2WidgetMixin. The media class specifies the required js files in a "hardcoded" manner so we cannot specify the order they are loaded. We must therefore override the js files being loaded by specifying our own media class. This can be done by adding the "extend=False" attribute to your media class in your form (to not extend the existing library media class) and then manually specifying the order of js files, with your translation file included in the loaded js files (as seen above). You can read more about the Media class and the extend attribute [here]( https://docs.djangoproject.com/en/1.9/topics/forms/media/#extend).

**Comment by owen9825** [comment]
I overwrote the Media class of the widget, but somehow the language file was being loaded too late and the first form kept suffering the phenomenon of the missing language file. I managed to work around it by loading the necessary JavaScript files in order before any of the forms were rendered.
```
{% load i18n %}
{% load cache %}
{% load l10n %}

{% get_current_language as LANGUAGE_CODE %}
            {% cache 500 autocompletion_language LANGUAGE_CODE %}
                {% if LANGUAGE_CODE != 'en' %}
                    <script type="text/javascript" src="{% static 'autocomplete_light/jquery.init.js' %}"></script>
                    <script type="text/javascript" src="{% static 'autocomplete_light/autocomplete.init.js' %}"></script>
                    <script type="text/javascript" src="{% static 'autocomplete_light/vendor/select2/dist/js/select2.full.js' %}"></script>
                    {% with "autocomplete_light/vendor/select2/dist/js/i18n/"|add:LANGUAGE_CODE|add:".js" as language_file %}
                        <script type="text/javascript" src="{% static language_file %}"></script>
                    {% endwith %}
                {% endif %}
            {% endcache %}
```
