### ISSUE TITLE
Support for non forms.ModelForm

### ISSUE THREAD

**Issue by cereblanco** [yourlabs/django-autocomplete-light#719]
Is there any example on how to use this in a non forms.ModelForm?
Say use it in a forms.Form?

```
class Sample(forms.Form)
      recipients = forms.CharField(widget= autocomplete.ModelSelect2Multiple(url='people-autocomplete'))
      message = forms.CharField(widget= widget = Textarea())
```

I'm encountering this error:

Exception Value: 'list' object has no attribute 'queryset'
Exception Location:	/usr/local/lib/python2.7/dist-packages/dal/widgets.py in filter_choices_to_render, line 112

**Comment by jpic** [comment]
The problem is not the forms.Form support, that wouldn't really change much.

Here you re trying to use a model widget, so it would have a model instance
value, that's not compatible with the charfield which works with string
value. In addition you re trying to use a multiple model widget which value
is not even a model but a list of models, so that is even less compatible
with charfield.

My advice is to first try to get your form to work with djangos Select and
/ or SelectMultiple, and then try to replace it with autocompletes. Here I
think you re trying to grasp too much at once my dear friend !

**Comment by cereblanco** [comment]
Got it! I worked with SelectMultiple, passed some key-pairs to it, and transformed it to autocomplete  using select2. Thank you.
