### ISSUE TITLE
"Name" as query field

### ISSUE THREAD

**Issue by jsanchezs** [yourlabs/django-autocomplete-light#769]
Hi again ;)

I was trying to use `Select2QuerySetView`, overwriting `get_queryset()` but using `super().get_queryset()`  (too many mixings in this project, it seems xD).

I had a problem, because of [here](https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal/views.py#L69), in the `get_queryset` method at `BaseQuerySetView`, it is trying to find if `q` is contain in `name` field. The `name` field is not in my model and it crash.

Could this field be a variable? Does It makes sense?

Thanks for the project =D

**Comment by jpic** [comment]
Well there's an example for overriding the queryset at the beginning of the tutorial: http://django-autocomplete-light.readthedocs.io/en/master/tutorial.html#create-an-autocomplete-view

If we were to have something that would allow more complex configuration like we [had in v2](http://django-autocomplete-light.readthedocs.io/en/2.3.1/api.html#module-autocomplete_light.autocomplete.model), then it should not be part of DAL but of another package.

Why ? Because if we're creating some class that allows configuration such as search_names, split_words and all to create a queryset: it has nothing to do with autocompletion in itself, could be used for other things than autocompletion and is completely generic.

If you don't want to work on this alone and you want to create such an app and drive its development within the yourlabs community and provide a Mixin to use with DAL autocompletes I'm all ears. We've had many contributions on this feature in v2 including by very experienced developers so it's definitely something we're all interrested in and that's going to get contributions. So mostly you'll have to setup the repository, documentation, tests & continuous integration, release process with the features you want and then just let it live its life of open source software :)

**Comment by jsanchezs** [comment]
Wow, thank you for invite me to start this kind of project, I am sure that working with yourlabs community would be a great experience, but now I could not spend so much time on this project, something that it is really needed at the beginning. I will consider it in a few months =)

Anyway, I like your point of view about django-autocomplete-light, avoiding to implement generic solutions that could be in different projects and leaving this one for just one purpose.

So the issue has no more sense for me. I close it.

Thank you =D
