### ISSUE TITLE
Static files not loading for autocomplete in non-admin

### ISSUE THREAD

**Issue by aaishgit** [yourlabs/django-autocomplete-light#805]
Template code:
```
{% load static %}
<DOCTYPE HTML>
<html>
	<head>
		<title>Create a Course</title>
		</head>
	<body>
	 	<h1> Register a new course here</h1>
	 	{% if course_registered %}
	 	Rango says: <strong>Thanks</strong>
	 	<a href="/faculty">Return to homepage</a> <br />
	 	{% else %}
	 	<strong>register here</strong>
		 	<form id="course_form" method="post" action="/faculty/create_course/"
		 		enctype="multipart/form-data">
		 		{% csrf_token %}
		 		{{ course_form.as_p }}
		 		<h2>Select Students:</h2>
		 		{{ year_form }}
		 		{{ branch_form }}
		 		<input type="submit" name="submit" value="Register" />
		 	</form>
	 	{% endif %}
	</body>
	<script type="text/javascript" src="{% static 'admin/js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'autocomplete_light/autocomplete.init.js' %}"></script>
	<script type="text/javascript" src="{% static 'autocomplete_light/select2.js' %}"></script>
	{{ form.media }}
</html>
```

I have run python manage.py collectstatic and collected my static files in static folder under root directory of my project. Also i have set my static folder in settings.py file.

**Comment by jpic** [comment]
Is the file actually there on the file system at the location it tries to read from ?

**Comment by aaishgit** [comment]
Yes these three files are in static directory. And also they are shown when I inspect element and check the js files being loaded.
'''<script type="text/javascript" src="{% static 'admin/js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'autocomplete_light/autocomplete.init.js' %}"></script>
	<script type="text/javascript" src="{% static 'autocomplete_light/select2.js' %}"></script>'''

**Comment by jpic** [comment]
No, the title of this issue is "Static files not loading", and now you say that the static files are loading. I don't even understand what's going wrong. Could you please try to put some effort in describing your actual issue because I'm not in your head ;) If possible, try to make a mini project where you can reproduce your issue so we can debug it quickly !

**Comment by rbansalrahul6** [comment]
I am also facing similar kind of issue. I followed your tutorial for autocomplete outside admin site and also checked your test project for the same.
[Autocomplete Tutorial](https://django-autocomplete-light.readthedocs.io/en/master/tutorial.html)
[Autocompletes outside admin test project](https://github.com/yourlabs/django-autocomplete-light/tree/master/test_project/select2_outside_admin)
I am having problem in loading required static files.
This is code snippet for template from your tutorial
```
{% extends 'base.html' %}
{# Don't forget that one ! #}
{% load static %}

{% block content %}
<div>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" />
    </form>
</div>
{% endblock %}

{% block footer %}
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>

{{ form.media }}
{% endblock %}
```
Can you please explain the link of javascript file provided by you? How should I link the required javascript files in my template?
`{% static 'admin/js/vendor/jquery/jquery.js' %}`
I put the same link of javascript in my template and it shows 404 error.
Should I run `python manage.py collectstatic` and collect all static files in my root folder and refer to javascript files thereafter?
Also I have tested my autocomplete views inside admin. They are working fine. But I am facing problem in loading them outside admin site.
I am stuck. Please help me.

**Comment by jpic** [comment]
"I am having problem in loading required static files."

What's happening on the network ? Does the Network tab of the firefox or webkit inspector report any error ?

**Comment by jpic** [comment]
I just spent 12 minutes creating a new project from scratch and the static files all load fine and the autocomplete widget i've setup works fine: https://github.com/jpic/rbansalrahul6_project

Create some groups and a user and visit localhost:8000/user/1/

Please either make a simple demo project either make a better report of what you're experiencing, here are links which are a must-read and that will definitely help you understand what we need in order to be of any help :)

http://www.chiark.greenend.org.uk/~sgtatham/bugs.html
http://stackoverflow.com/help/how-to-ask


Otherwise, can you'll be more lucky asking on StackOverflow ?

**Comment by jpic** [comment]
Also, here is the diff, from a fresh django-admin started project, to a working DAL example outside the admin: https://github.com/jpic/rbansalrahul6_project/commit/9b984719b106293b4254477e174c7e4c0b9ba904

**Comment by tamhv** [comment]
@rbansalrahul6 @aaishgit hi guys  "I am having problem in loading required static files." 💃 
and i forgot this line `{{ form.media }}`

**Comment by rashmitpankhania** [comment]
even I have the same problem when I try to load my CSS file it only shows admin autocomplete in the link tag

**Comment by webtweakers** [comment]
Same problem here: the required media files do not load.

I checked out the example project of @jpic, which works indeed perfectly.

But if I change the view to a `FormView`, the form to a normal `forms.Form` instead of a `ModelForm`, and use `autocomplete.ListSelect2` instead of `autocomplete.ModelSelect2Multiple`, then it stops working. The media files, as described in `dal_select2.widgets.Select2WidgetMixin`, will not be rendered in the html anymore.

In fact, from a python shell:

```
In [1]: from rbansalrahul6_project.urls import UserForm

In [2]: u = UserForm()

In [3]: u.media
Out[3]: <django.forms.widgets.Media at 0x1055298d0>

In [4]: u.media.render()
Out[4]: u''
```

That's the result with this form and view in the urls.py:

```
class UserForm(forms.Form):
    groups = fields.Select2ListChoiceField()

    class Meta:
        widgets = dict(
            groups=autocomplete.ListSelect2('group_autocomplete'),
        )
        exclude = []


class UserUpdate(generic.FormView):
    template_name = 'auth/user_form.html'
    form_class = UserForm
```

For now I'm not sure why this happens, as both `autocomplete.ModelSelect2Multiple` and `autocomplete.ListSelect2` inherit from `Select2WidgetMixin`, which holds the media...

**Comment by jpic** [comment]
Does it work when you remove UserForm.Méta.widgets ? The field should deal
with the widget by default shouldn't it ?

**Comment by jpic** [comment]
Also, what versions have you tried ?

**Comment by webtweakers** [comment]
"Does it work when you remove UserForm.Méta.widgets ? The field should deal
with the widget by default shouldn't it ?"

Indeed, I just figured my mistake and deleted the message. It's working now.

**Comment by jpic** [comment]
Awesome, thanks for your feedback

**Comment by hackedaccount** [comment]
I used this autocomplete in my project and it is outside admin. Its working on my localhost. But on server, It is not. Here I can see problems nut not the solutions. Can anyone enlighten me please on my issue.
