### ISSUE TITLE
Large Querysets make it impossible to render

### ISSUE THREAD

**Issue by AndreasDickow** [yourlabs/django-autocomplete-light#898]
When handling large querysets (several 1000 entries), i don't want to render all options because i search them dynamically with DAL.  
So if i do init a form like this to prevent rendering all options:
```python
class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        ...
        widgets = {
            'zipcode': autocomplete.ModelSelect2('zipcode-autocomplete'),# yields Zipcode.objects.all()
        }
    def __init__(self,*args, **kwargs):
        super(CompanyForm, self).__init__(*args, **kwargs)
        iterator = ModelChoiceIterator(self.fields['zipcode'])
        choices = [iterator.choice(obj) for obj in  Zipcode.objects.none()]
        self.fields['zipcode'].choices = choices
```
the form will not validate

**Comment by AndreasDickow** [comment]
my current workaround:
def clean_fields(self, exclude=None):
     return super(Company, self).clean_fields(exclude=['zipcode', ])

**Comment by jpic** [comment]
I'm very surprised by your post and have no idea what you're doing, or what you're trying to achieve. DAL is not supposed to render all choices, only selected choices: https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal/widgets.py#L132

Are you sure you code shows the initial value of the form ?
Are you sure a user can't submit your form with a zipcode id that doesn't exist (yet) in the database now that the field is not cleaned anymore ?

**Comment by AndreasDickow** [comment]
this is not about the select2 widget part, you can see what I mean in browser inspect 
css class .select2-hidden-accessible inside the select options are all rendered to the template, although nobody needs them. As result of rendering 100k options the template renderer crashes

**Comment by jpic** [comment]
Come on, do you really think we maintain DAL for what 6 years for anything else than rendering selects for millions of options ? Please credit us with basic intelligence ^^
Is there any way to reproduce this in the test_project ?
Otherwise, could you fork and add an app to reproduce this in the test_project ?

**Comment by jpic** [comment]
I have just tried inserting 100 000 objects in the select2_foreign_key test app as such:

    In [1]: from select2_foreign_key.models import TModel

    In [2]: for i in range(0, 100000): TModel.objects.create(name='lol%s' % i)

The page rendered without any problem.

If I were you, I would try `ModelSelect2(url='zipcode-autocomplete')` instead of `ModelSelect2('zipcode-autocomplete')`, like in the documentation, to have the system work as expected.
