### ISSUE TITLE
performance with multiple widgets with large querysets each

### ISSUE THREAD

**Issue by nivcaner** [yourlabs/django-autocomplete-light#969]
I notice a big performance issue when having multiple widgets in one page each with a large queryset.
The issue is caused by the method WidgetMixin.filter_choices_to_render
The method goes over each of the choices for the widget (thousands in my case) and compares each choice to the selected_choices.
I managed to improve the bottleneck like this:
```python
def filter_choices_to_render(self, selected_choices):
    """Replace self.choices with selected_choices."""
    if not selected_choices:
        self.choices = []
    elif len(selected_choices) == 1:
        qs = self.choices.queryset.filter(pk=selected_choices[0])
        self.choices = [(qs[0].pk, qs[0])]
    else:
        self.choices = [c for c in self.choices if
                        six.text_type(c[0]) in selected_choices]

```
if the widget has nothing selected yet - I just empty out the self.choices
if the widget has one selected choice, I use the self.choices.queryset to find that element instead of traversing thousands of items in a list.

This has improved one of my page loads from over 2 minutes to 7 seconds...

**Comment by jpic** [comment]
That's because you need a widget which supports querysets, see this mixin:

https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal/widgets.py#L181

Is there any reason you're not using [ModelSelect2](https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal_select2/widgets.py#L77) which has it?

**Comment by prashanthps** [comment]
I think its because the current implementation of filter_choices_to_render in ModelSelect2 loads the entire queryset (which becomes a perf bottleneck if there are several 1000s of choices) by default, _before_ the end user has a chance to type the first character in the widget. "if the widget has nothing selected yet - I just empty out the self.choices" is exactly what we need. @nivcaner How can I try out your update in my code?

**Comment by nivcaner** [comment]
@prashanthps I just monkey patched the `filter_choices_to_render` method with the code I posted and it works nicely

**Comment by jpic** [comment]
Lol ok monkey patch it instead of using the mixin that does it it's your choice.
